image: docker:stable

variables:
  DOCKER_REGISTRY: docker.miracum.org
  PROJECT_PATH: /miracum-etl/loinc-conversion
  IMAGE_PATH: $DOCKER_REGISTRY$PROJECT_PATH

.docker_registry:
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME $DOCKER_REGISTRY --password-stdin
  after_script:
    - docker logout $DOCKER_REGISTRY

.job_defaults:
  only:
    - master
    - merge_requests

include:
  - project: "devops/ci-templates"
    file: "/preflight/.tidy-files.yml"
  - project: "devops/ci-templates"
    file: "/linting/.yamllint.yml"
  - project: "devops/ci-templates"
    file: "/linting/.hadolint.yml"
  - project: "devops/ci-templates"
    file: "/linting/.markdownlint.yml"
  - project: "devops/ci-templates"
    file: "/versioning/.semantic-release-get-version.yml"
  - project: "devops/ci-templates"
    file: "/image-scanning/.trivy-scan.yml"

stages:
  - preflight
  - lint
  - version
  - build
  - test
  - release

check file tidiness:
  extends: .job_defaults
  variables:
    IGNORE: ".git,*.min.js,*.min.css,*.md"

hadolint:
  extends: .job_defaults

yamllint:
  extends: .job_defaults

markdownlint:
  extends: .job_defaults

get next version:
  extends: .job_defaults

build:
  stage: build
  extends:
    - .job_defaults
    - .docker_registry
  script:
    - export VERSION=$(cat .VERSION)
    - docker build -t $IMAGE_PATH:$CI_COMMIT_SHORT_SHA --build-arg VERSION=$VERSION .
    - docker push $IMAGE_PATH:$CI_COMMIT_SHORT_SHA

trivy:
  extends: .job_defaults
  allow_failure: true
  variables:
    IMAGE_FQN: $DOCKER_REGISTRY$PROJECT_PATH:$CI_COMMIT_SHORT_SHA

e2e:
  image:
    name: docker/compose:1.25.4
    entrypoint: [""]
  stage: test
  extends:
    - .job_defaults
    - .docker_registry
  before_script:
    - export IMAGE_TAG=$CI_COMMIT_SHORT_SHA
  script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.yml up --abort-on-container-exit
  after_script:
    - docker-compose -p $CI_PROJECT_NAME-$CI_JOB_ID -f tests/e2e/docker-compose.yml down --remove-orphans

push to harbor:
  image: docker:git
  stage: release
  extends: .docker_registry
  script:
    - export IMAGE_TAG=v$(cat .VERSION)
    - docker pull $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_PATH:$CI_COMMIT_SHORT_SHA $IMAGE_PATH:$IMAGE_TAG
    - docker push $IMAGE_PATH:$IMAGE_TAG
  only:
    - master

create gitlab  release:
  image: docker.miracum.org/miracum-devops/semantic-release
  stage: release
  script:
    - npx semantic-release
  only:
    - master
